### ISSUE TITLE
Extending the front-end components

### ISSUE THREAD

**Issue by meysammahfouzi** [rainlab/userplus-plugin#13]
I was hoping to find out how to extend the `User Plugin`'s components by looking at the code of this plugin, but realized this plugin has only extended the back-end form fields. It would be great to have a tutorial to address the questions raised about extending front-end components, like this one: 

https://octobercms.com/forum/post/extend-user-component
http://stackoverflow.com/q/34681748/69537
https://octobercms.com/forum/post/how-to-create-custom-user-registration-form-with-fields-from-plugin-extension

[This old tutorial](https://vimeo.com/108040919) explains how to extend the `user plugin`, but does not say anything about extending the front-end components of that plugin (e.g. how to add new fields to the registeration form?)
Many users may be currently ending up copy pasting and duplicating stuff which can lead to maintenance headaches in future.

**Comment by daftspunk** [comment]
[Watch + Learn](https://www.youtube.com/watch?v=gBGVOspf1NY) just did a video about this.

**Comment by meysammahfouzi** [comment]
@daftspunk Thank you for the update.  
Fields added using `$model.addFillable()` are always inserted into database and when they are not provided by user, empty string will be inserted. Is it possible to specify whether empty string or `NULL` should be inserted into database for empty fields?

**Comment by daftspunk** [comment]
There is the `Nullable` trait that handles thing (converts empty strings to NULL). I wasn't aware of this, perhaps it is a Laravel / Eloquent thing?

**Comment by meysammahfouzi** [comment]
@daftspunk How can I extend the `User` model and add nullable fields to it?

**Comment by Codenator81** [comment]
@daftspunk On youtube video explain when new field added to User table but how do it when I have relation like User->profile->phone. How I can add phone to register form and save it?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
