### ISSUE TITLE
User plus injects fields into any pop-up user related form

### ISSUE THREAD

**Issue by mohsin** [rainlab/userplus-plugin#14]
This is a follow up of issue #5 and I’ve recreated the steps using the [Test plugin](https://github.com/daftspunk/oc-test-plugin).

1. Install the necessary plugins for User Plus to work and add oc-test-plugin.
2. Make the changes of [this fork commit](https://github.com/SaifurRahmanMohsin/oc-test-plugin/commit/950b74f69155a482e47f340333758ad756a05414).
3. Goto Users controller, Extras tab, click Add comment and add one comment. Now click on the comment which you added, this should come as a pop-up but instead I get this:

<img width="1440" alt="screen shot 2016-11-30 at 12 18 03" src="https://cloud.githubusercontent.com/assets/1699753/20742942/72125c72-b6f9-11e6-8556-299c1838e792.png">

I tried removing the country and state fields from the UserPlus plugin code and to my surprise, the profile tab with it’s fields get added to the original relation’s fields which should appear in the popup i.e. the comments appear and also the extra **Profile** tab which the UserPlus adds ([screenshot](http://i.imgur.com/GpEtdBq.png)). This isn’t the right behaviour as it should not inject it’s fields to this relation.

P.S. In the fork’s commit, I removed `type: partial` from `error_button` field because that gave a missing partial error. That’s probably a different bug and I think you may have forgotten to add the error_button partial file to the test plugin. So, I just removed it to show this issue’s error instead.

**Comment by daftspunk** [comment]
Sorry to say I am getting completely different results.

1. Adding a comment works +OK
1. Clicking the comment works +OK
1. There is no "Profile" tab injecting in to my comment.

This is probably because there have been numerous improvements to the UserPlus plugin, but the version was never bumped. Try updating to v1.0.4 and hopefully you get the same result as me.

**Comment by mohsin** [comment]
The version bump fixed it. Thank you.
