### ISSUE TITLE
"plugins" folder inside the rainlab\userplus plugin folder with copies of both User and Location plugins?

### ISSUE THREAD

**Issue by mpenna** [rainlab/userplus-plugin#18]
This is a question...

I installed the UserPlus plugin yesterday so to check it out, and at first the installation didn't work, but once I installed the Location plugin and tried installing UserPlus once again, it eventually worked. But now one thing strikes me as kind of weird. Inside the rainlab\userplus plugin folder, there's another plugin folder with what apparently seems to be full copies of both the Location and the User plugins. Is it supposed to be like that? If so, why?

**Comment by vojtasvoboda** [comment]
Same here:

![snimek obrazovky 2017-03-26 v 16 41 06](https://cloud.githubusercontent.com/assets/374917/24332215/0bf054a8-1243-11e7-8c34-2c583528806a.png)

**Comment by LukeTowers** [comment]
Hmm, this might have been a temporary error with the build process on the October marketplace. I'm guessing this plugin probably needs to be rebuilt on the marketplace to clean out those artifacts. @daftspunk any input?

**Comment by daftspunk** [comment]
Confirmed. This odd nesting exists in the marketplace source version. Looks like composer might be bringing them in as deps.

**Comment by daftspunk** [comment]
This is fixed!
