### ISSUE TITLE
RainLab.Notify isn't automatically installed when installing from marketplace

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/userplus-plugin#23]
When installing through the updates and plugins section in the CMS, not all the `required` plugins are installed. The `RainLab.Location` Plugin is installed, but the `Notify` plugin is not.

**Steps:**
1: Install `RainLab.User`
2: Install `RainLab.UserPlus`

The dependency manager within October now installs the ``Location`` plugin, but does not install ``Notify``. This is not a problem neccesarily, but it's weird UX. October does **not** give any form of error, and does not show the `UserPlus` plugin in the list of installed plugins. 

Only when installing the Notify plugin the `UserPlus` plugin appears in the list.

This bug is somewhat related to already closed issues #7 and #9 , only this has to do with the `Notify` plugin instead of `Location`.

**Comment by LukeTowers** [comment]
Sounds like a bug in how the marketplace handles changes in plugin dependencies. I'll talk to @daftspunk about it.

**Comment by LukeTowers** [comment]
@CptMeatball @daftspunk added the dependency link to the marketplace, it should work now.
