### ISSUE TITLE
When I try to extend the User form in my Plugin.php with a repeater widget using addFields() or addTabFields() this includes all fields of the User Plus form. 

### ISSUE THREAD

**Issue by briddle** [rainlab/userplus-plugin#30]
When I try to extend the User form in my Plugin.php with a repeater widget using addFields() or addTabFields() this includes all fields of the User Plus form. 

Inside Plugin.php on row 73 (in the extendUsersController() function) wrap 

$widget->addTabFields($config);

inside:

if($widget->isNested === false) {} 

Please see my post in the forum for details:

https://octobercms.com/forum/post/extending-a-form-with-a-repeater-widget-using-addfields-or-addtabfields-includes-all-fields-of-the-parent-form?page=1#post-26331

**Comment by LukeTowers** [comment]
@briddle feel free to make a PR

**Comment by daftspunk** [comment]
Fixed by #31
