### ISSUE TITLE
Location not updating from frontend form

### ISSUE THREAD

**Issue by vosco88** [rainlab/userplus-plugin#34]
Hi, 
I have user plus installed everythings works great the only thing that was causing me trouble was updating country and state from frontend user profile page. 

After I've put this part of code for country
`$model->addFillable(['country_id']);` 
into the `Plugin.php` in the `extendUserModel()` function after implement declaration  `$model->implement[] = 'RainLab.Location.Behaviors.LocationModel';` it starts working. Not quite sure if this is a bug with this plugin or with the Location, or if I am doing something wrong here

**Comment by mennax** [comment]
I confirm. I can't update country_id and state_id from frontend user profile page.
thank's @vosco88. in userplus/Plugin.php 

This fix it:

protected function extendUserModel()
{
	UserModel::extend(function($model) {
		$model->addFillable([
			'phone',
			'mobile',
			'company',
			'street_addr',
			'city',
			'zip',
			'state_id',  <--- ADD
			'country_id'  <--- ADD
		]);
...
}

**Comment by kosmonowt** [comment]
👍  here! that's got something to do with those lines here:

__LocationModel.php__ Line 33 ``if (count($guarded) === 1 && $guarded[0] === '*') {``

Anyone has got an idea what this shall serve?

**Comment by LukeTowers** [comment]
@kosmonowt that checks to see if all model attributes are guarded (protected against mass assignment).

**Comment by kosmonowt** [comment]
@LukeTowers ok, sure. 
But IMHO it prevents the (appreciated) mass assignment for country_id from being applied, doesn't it?
For me, this appears contrary to the `addFillable()` in the LocationModel.

**Comment by LukeTowers** [comment]
@kosmonowt models can define $guarded or they can define $fillable, you shouldn't be using both. See https://github.com/rainlab/location-plugin/pull/53 for a more detailed discussion on the change.

**Comment by kosmonowt** [comment]
@LukeTowers I understand that and agree that's reasonable and best practice.
It's just somehow confusing, since it's not expilcitly mentioned and one would have to override the `$guarded` array of the User Model or add the `country_id` and `state_id` manually in some custom addFillable.

At least for me I took me quite a while to see why my `country_id` has not been saved. But when it resolves another error I see that it might be necessary.

**Comment by bennothommo** [comment]
@kosmonowt In fairness, it's mentioned in the docs: https://octobercms.com/docs/database/model#mass-assignment

> While $fillable serves as a "white list" of attributes that should be mass assignable, you may also choose to use $guarded. The $guarded property should contain an array of attributes that you do not want to be mass assignable. All other attributes not in the array will be mass assignable. So, $guarded functions like a "black list". Of course, you should use either $fillable or $guarded - not both:

Nevertheless, a fix to resolve this was made here: https://github.com/rainlab/user-plugin/pull/434.

Feel free to test that and let us know if it works for you.

**Comment by kosmonowt** [comment]
Alright. Seems to work for me.
Humbly apologizing for wasting everyone's time due to ignoring to RTFM.

**Comment by daftspunk** [comment]
`addFillable` is the way to go here, as suggested.
