### ISSUE TITLE
Plugin not Shown in October 3.1 and latest User Plugin

### ISSUE THREAD

**Issue by nnnext** [rainlab/userplus-plugin#38]
The complete plugin functions are missing in my installation with October v3.1 and User 1.6.2.
In October v2 i have all the additional fields at the user Details and the Menu with Import Export functions.

**Comment by daftspunk** [comment]
Hello @nnnext 

Thanks for your issue, and sorry to hear this plugin is not showing. Could you please try the following:

1. Navigate to the dashboard
2. Check the System Status panel for **Some Issues Need Attention.**
3. If it is there, click the **View** button

Do you see any messages like the one below?

>  The plugin XXX is a dependency but is not installed. Please install this plugin.

**Comment by nnnext** [comment]
thank you. yes it was the location and the notify dependency. thought all dependecies are installed automatically. sorry for that.

**Comment by daftspunk** [comment]
No worries. This is a gap in the UX. We have added a button that should make things easier. This screen has been added in v3.1.16:

![image](https://user-images.githubusercontent.com/1392869/197694827-9db8197d-c87d-447e-bc13-95788ec43013.png)
