### ISSUE TITLE
User plus injects fields into any pop-up user related form

### ISSUE THREAD

**Issue by firemankurt** [rainlab/userplus-plugin#5]
User plus injects it's fields into any pop-up form with relation to user.

Similar to a problem listed here: https://octobercms.com/forum/post/tabs-in-backend-popup-form?page=1

I am not sure how to prevent this because userplus extends user directly instead of a relationship such as one to one.  This was found when related kurt.jensen.cellphone plugin cellphone form was opened.

The cellphone plugin uses this code to extend form:

```
if (!post('_relation_field')) {
        UsersController::extendFormFields(function ($form, $model, $context) {

            if (!$model instanceof UserModel) {
                return;
            }

            if (!$model->exists) {
                return;
            }

            if ($form->getContext() != 'update' && $form->getContext() != 'preview') {
                return;
            }
            $form->addTabFields([
                'cellphones' => [
                    'label' => '',
                    'tab' => 'Mobile Phones',
                    'type' => 'partial',
                    'path' => '~/plugins/kurtjensen/cellphone/partials/_std_form.htm',
                ],
            ]);
        });
```

**Comment by daftspunk** [comment]
Can you provide a way for me to replicate this issue, perhaps using the [Test plugin](https://github.com/daftspunk/oc-test-plugin)? Or a screenshot? I'm not quite sure exactly what is happening.

**Comment by firemankurt** [comment]
https://drive.google.com/file/d/0BwJLIChm8ILtX0xtTk5aTXg5VW8/view?usp=sharing
Video showing me opening cellphone form.
Then I disable boot() function in userplus and try again.
Then finally I re-enable boot() function in userplus and try again.

The response for pop-up for cellphone form should be :  http://kopy.io/SkS6N
But with userplus it is : http://kopy.io/q9lsf

I have also given daftspunk access to repo on bitbucket for cellphone plugin.

**Comment by firemankurt** [comment]
Issue appears to be resolved now.

Not sure how, when or where but everything is working right now???

**Comment by mohsin** [comment]
@firemankurt Hey can you verify if this still persists? I published a plugin which extends the User plugin as well and a pop-up relation field. One of my users who uses User-plus reported this same behavior and he’s fully updated too so I think it exists. I will verify it too in a few hours and make a new issue request is needed.
