### ISSUE TITLE
Relies on Rainlab.Location plugin, no error on install

### ISSUE THREAD

**Issue by tobycatlin** [rainlab/userplus-plugin#9]
If you do not have the Location plugin installed the install will fail but indicates as successful. Highly confusing.

**Comment by daftspunk** [comment]
Missing dependencies are not as clear as they could be. We are working on a
solution for that. Thanks for reporting this.

**Comment by LukeTowers** [comment]
Closing this as https://github.com/octobercms/october/issues/36 was resolved
